openapi: 3.0.0
info:
  title: Users API
  description: API chupitos
  version: 1.0.0
servers:
  - url: "http://localhost:5002"
    description: localhost url

tags:
  - name: users
    description: When a customer decides to redeem a specific points, they initiate the redemption process.
    x-displayName: users
x-tagGroups:
  - firstName: users
    tags:
      - users

paths:
  /v1/users:
    get:
      summary: Retrieves events with registration status
      tags:
        - users
      responses:
        "200":
          description: return all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Users"
        "500":
          description: error given when an unexpected condition was encountered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                internal_server_error:
                  value:
                    status: 500
                    message: Internal server error

    post:
      summary: Create a new user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/Users"
      responses:
        "200":
          description: Return a new user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Users"
        "401":
          description: error given when the user is not logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                unauthorized:
                  value:
                    status: 401
                    message: Unauthorized
        "422":
          description: error given when some parameter is wrong
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                unprocessable_entity:
                  value:
                    status: 422
                    message: Unprocessable Entity
        "500":
          description: error given when an unexpected condition was encountered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                internal_server_error:
                  value:
                    status: 500
                    message: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Users:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        isAdmin:
          type: boolean
        isSuperAdmin:
          type: boolean
        role:
          type: string
        uid:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
